### ISSUE TITLE
Error: "Interface 'PHP_CodeSniffer_Sniff' not found"

### ISSUE THREAD

**Issue by Flimm** [WordPress-Coding-Standards/WordPress-Coding-Standards#1154] opened 2017-09-22 10:37 UTC
Here is how to reproduce this bug:

```
$ composer require --dev dealerdirect/phpcodesniffer-composer-installer
$ composer require --dev wp-coding-standards/wpcs
$ touch hi.php
$ vendor/bin/phpcs hi.php
PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in test/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php on line 35
PHP Stack trace:
PHP   1. {main}() test/vendor/squizlabs/php_codesniffer/bin/phpcs:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() test/vendor/squizlabs/php_codesniffer/bin/phpcs:18
PHP   3. PHP_CodeSniffer\Runner->init() test/vendor/squizlabs/php_codesniffer/src/Runner.php:70
PHP   4. PHP_CodeSniffer\Ruleset->__construct() test/vendor/squizlabs/php_codesniffer/src/Runner.php:294
PHP   5. PHP_CodeSniffer\Ruleset->registerSniffs() test/vendor/squizlabs/php_codesniffer/src/Ruleset.php:215
PHP   6. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/src/Ruleset.php:1103
PHP   7. include() test/vendor/squizlabs/php_codesniffer/autoload.php:167
PHP   8. spl_autoload_call() test/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php:26
PHP   9. PHP_CodeSniffer\Autoload::load() test/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php:26
PHP  10. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/autoload.php:134
PHP  11. include() test/vendor/squizlabs/php_codesniffer/autoload.php:167
PHP  12. spl_autoload_call() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionParameterSniff.php:21
PHP  13. PHP_CodeSniffer\Autoload::load() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionParameterSniff.php:21
PHP  14. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/autoload.php:134
PHP  15. include() test/vendor/squizlabs/php_codesniffer/autoload.php:167
PHP  16. spl_autoload_call() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php:27
PHP  17. PHP_CodeSniffer\Autoload::load() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php:27
PHP  18. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/autoload.php:134
PHP  19. include() test/vendor/squizlabs/php_codesniffer/autoload.php:167

Fatal error: Interface 'PHP_CodeSniffer_Sniff' not found in test/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php on line 35

Call Stack:
    0.0002     356272   1. {main}() test/vendor/squizlabs/php_codesniffer/bin/phpcs:0
    0.0020     571776   2. PHP_CodeSniffer\Runner->runPHPCS() test/vendor/squizlabs/php_codesniffer/bin/phpcs:18
    0.0102     926232   3. PHP_CodeSniffer\Runner->init() test/vendor/squizlabs/php_codesniffer/src/Runner.php:70
    0.0139    1150960   4. PHP_CodeSniffer\Ruleset->__construct() test/vendor/squizlabs/php_codesniffer/src/Runner.php:294
    0.0143    1155472   5. PHP_CodeSniffer\Ruleset->registerSniffs() test/vendor/squizlabs/php_codesniffer/src/Ruleset.php:215
    0.0144    1155472   6. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/src/Ruleset.php:1103
    0.0149    1259496   7. include('test/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php') test/vendor/squizlabs/php_codesniffer/autoload.php:167
    0.0149    1259496   8. spl_autoload_call() test/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php:26
    0.0149    1259576   9. PHP_CodeSniffer\Autoload::load() test/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/NamingConventions/PrefixAllGlobalsSniff.php:26
    0.0150    1260136  10. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/autoload.php:134
    0.0151    1282440  11. include('test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionParameterSniff.php') test/vendor/squizlabs/php_codesniffer/autoload.php:167
    0.0151    1282440  12. spl_autoload_call() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionParameterSniff.php:21
    0.0151    1282520  13. PHP_CodeSniffer\Autoload::load() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionParameterSniff.php:21
    0.0151    1282744  14. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/autoload.php:134
    0.0154    1328672  15. include('test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php') test/vendor/squizlabs/php_codesniffer/autoload.php:167
    0.0154    1328672  16. spl_autoload_call() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php:27
    0.0154    1328712  17. PHP_CodeSniffer\Autoload::load() test/vendor/wp-coding-standards/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php:27
    0.0154    1328824  18. PHP_CodeSniffer\Autoload::loadFile() test/vendor/squizlabs/php_codesniffer/autoload.php:134
    0.0167    1553088  19. include('test/vendor/wp-coding-standards/wpcs/WordPress/Sniff.php') test/vendor/squizlabs/php_codesniffer/autoload.php:167
```

I am using the following `phpcs.xml` file:

```xml
<?xml version="1.0"?>
<ruleset name="PHP_CodeSniffer">
  <description />
  <file>.</file>
  <arg name="extensions" value="php,inc,lib"/>
  <rule ref="WordPress.NamingConventions.PrefixAllGlobals">
    <properties>
      <property name="prefixes" type="array" value="my_prefix,tgmpa" />
  </properties>
  </rule>
</ruleset>
```

Here is my version information:

```
$ php --version
PHP 7.1.8 (cli) (built: Aug  7 2017 15:02:45) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
$ vendor/bin/phpcs --version
PHP_CodeSniffer version 3.1.0 (stable) by Squiz (http://www.squiz.net)
$ cat composer.json
{
    "require-dev": {
        "dealerdirect/phpcodesniffer-composer-installer": "^0.4.3",
        "wp-coding-standards/wpcs": "^0.13.1"
    }
}
```

I do meet the minimum requirements laid out in README.md:

> The WordPress Coding Standards require PHP 5.3 or higher and PHP CodeSniffer version 2.9.0 or higher. As of version 0.13.0, the WordPress Coding Standards are compatible with PHPCS 3.0.2+. In that case, the minimum PHP requirement is PHP 5.4.

**Comment by JDGrimes** [comment] 2017-09-22 13:19
The problem is with your `phpcs.xml`. You need to first include the WordPress ruleset, then set the property of one of the sniffs. Adding `<rule ref="WordPress" />` fixed the error for me.

**Comment by Flimm** [comment] 2017-09-22 13:42
@JDGrimes That does fix the error, but now, unfortunately a bunch of sniffs that I didn't want to enable are enabled.

**Comment by JDGrimes** [comment] 2017-09-22 15:06
You could try just `<rule ref="WordPress-Core" />` instead, if that is more what you wanted. I don't know if there is another way to include just a particular sniff or not. Perhaps it is supposed to work like you were doing it before, and it is a bug that it doesn't. Maybe @jrfnl has some insight?

**Comment by jrfnl** [comment] 2017-09-22 15:26
@Flimm Yes, this is a known upstream issue unfortunately. It was previously reported here (together with another upstream bug) in #1087.
The upstream issue has been reported here: https://github.com/squizlabs/PHP_CodeSniffer/issues/1582.

There are three ways to get around this bug for now:
* Either - as @JDGrimes suggested - include a complete ruleset and exclude the categories/sniffs you don't want.
* Or - and considering you are using Composer and the location is therefore predictable - including the WPCS autoload directive in your `phpcs.xml` ruleset file:
    ```xml
    <autoload>./vendor/wp-coding-standards/wpcs/WordPress/PHPCSAliases.php</autoload>
    ``` 
* If all you want to do is check the prefixes and you don't intend to add any other sniffs to the ruleset, you could run the following command from the command line instead of using a custom ruleset:
```bash
phpcs . --standard=WordPress --sniffs=WordPress.NamingConventions.PrefixAllGlobals --runtime-set prefixes my_prefix,tgmpa --extensions=php,inc,lib 
```

Marking this as a duplicate of #1087

**Comment by Flimm** [comment] 2017-09-22 17:15
Thank you so much for the explanation!

**Closed** 2017-09-22 17:15 UTC
Labels: Status: Duplicate

**Comment by GaryJones** [comment] 2017-09-22 21:26
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/PHPCS-3-and-testing-individual-sniffs
