### ISSUE TITLE
Expected 1 space before closing PHP tag; 0 found .

### ISSUE THREAD

**Issue by CheoWalker** [WordPress-Coding-Standards/WordPress-Coding-Standards#1065] opened 2017-07-25 16:52 UTC
Expected 1 space before closing PHP tag; 0 found show as a fixable issue, but when running the code sniffer fix the issue is not fix and I have to manual make the fix.

**Comment by CheoWalker** [comment] 2017-07-26 12:04
I am using version 0.12.0 of WPCS and version 2.9.1 of PHPCS.
`<?php if ( get_comment_pages_count() > 1 && get_option( 'page_comments' ) ) : // Are there comments to navigate through? ?>`

**Comment by jrfnl** [comment] 2017-07-26 12:19
@CheoWalker Thanks for getting back to me. Your code sample confirms that this is a duplicate of #1017.

This is fixed upstream in PHPCS itself. The fix is contained within the PHPCS 3.0.2 release and will also be in the PHPCS 2.9.2 release.

**Closed by jrfnl** 2017-07-26 12:19 UTC
Labels: Status: Awaiting Feedback
