### ISSUE TITLE
FunctionRestricted ignores warning in some cases.

### ISSUE THREAD

**Issue by emgk** [WordPress-Coding-Standards/WordPress-Coding-Standards#1049] opened 2017-07-24 19:29 UTC
In WordPress-VIP there are many WordPress functions which are restricted to use due to not caching the data, slow performance and other various reasons. 

`WordPress_Sniffs_VIP_RestrictedFunctionsSniff` sniff works great when I call the function in the normal way. for Eg.` wp_remote_get( 'http://example.com' );` it will throw the WARNING. 

> wp_remote_get() is highly discouraged, please use vip_safe_wp_remote_get() instead.

But it may be the case that these functions are calling using `call_user_func()`, `call_user_func_array()`. 

for Eg. `call_user_func( 'wp_remote_get', 'http://example.com' );`

In this case, PHPCS showing no warning when calling the restricted function  `call_user_func()`, `call_user_func_array()`.

Environment:
**phpcs** : v2.9 , 
**wpcs:** develop branch

Let me know any further info needed.

**Comment by JDGrimes** [comment] 2017-07-24 19:33
Thanks for the report @emgk. This is actually a duplicate of #611. It will be fixed by #843.

**Closed by JDGrimes** 2017-07-24 19:33 UTC

**Comment by GaryJones** [comment] 2017-07-24 22:10
@JDGrimes Bonus points for sneaking in "duplicate of" keyword :-)

**Comment by JDGrimes** [comment] 2017-07-24 22:23
@GaryJones I actually didn't realize that GitHub looks for that keyword until after posting. 😄

**Comment by jrfnl** [comment] 2017-07-24 22:28
@JDGrimes It's a [recent feature](https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates) and even has it's own "saved reply" which is available to everyone ;-)

**Comment by khacoder** [comment] 2018-01-25 02:44
I am developing a plugin that uses wp_remote_get() to retrieve reCaptcha response.
I get the above error on sniff 

> wp_remote_get() is highly discouraged, please use vip_safe_wp_remote_get() instead.

What is my alternative if I don't have access to the vip_safe_wp_remote_get() function?

**Comment by jrfnl** [comment] 2018-01-25 03:04
@khacoder Your question is completely unrelated to the issue reported in this thread. It may refer to the same function, but it is most definitely not the same issue. So, please do not pollute issues with unrelated questions. If you can't find an issue which already covers your question, open a new ticket.

Aside from that, if you don't run on the `VIP` platform, you can safely exclude the `WordPress.VIP` sniffs. Also have a look at #1288.

**Comment by khacoder** [comment] 2018-01-25 04:58
So polite of you to offer your help.

Many thanks :)
