### ISSUE TITLE
Failed when running command with Wordpress

### ISSUE THREAD

**Issue by sakonachhoeurng** [WordPress-Coding-Standards/WordPress-Coding-Standards#1230] opened 2017-11-16 08:32 UTC
`php version 7.1.11`
`squizlabs/php_codesniffer (2.9.0)`
I install vai composer with `squizlabs/php_codesniffer (2.9.0)`
Then I run configure point to install path and path to wpcs
And I run command `phpcs --standard=WordPress wp-content/themes/kymenlaaksonjate/template-service.php`
Then got error below
```
PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in /home/sakona/dev/wpcs/WordPress/Sniff.php on line 36
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpcs:0
PHP   2. PHP_CodeSniffer\Runner->runPHPCS() /usr/local/bin/phpcs:6
PHP   3. PHP_CodeSniffer\Runner->init() phar:///usr/local/bin/phpcs/src/Runner.php:2
PHP   4. PHP_CodeSniffer\Ruleset->__construct() phar:///usr/local/bin/phpcs/src/Runner.php:2
PHP   5. PHP_CodeSniffer\Ruleset->registerSniffs() phar:///usr/local/bin/phpcs/src/Ruleset.php:2
PHP   6. PHP_CodeSniffer\Autoload::loadFile() phar:///usr/local/bin/phpcs/src/Ruleset.php:2
PHP   7. include() phar:///usr/local/bin/phpcs/autoload.php:2
PHP   8. spl_autoload_call() /home/sakona/dev/wpcs/WordPress/Sniffs/DB/RestrictedClassesSniff.php:29
PHP   9. PHP_CodeSniffer\Autoload::load() /home/sakona/dev/wpcs/WordPress/Sniffs/DB/RestrictedClassesSniff.php:29
PHP  10. PHP_CodeSniffer\Autoload::loadFile() phar:///usr/local/bin/phpcs/autoload.php:2
PHP  11. include() phar:///usr/local/bin/phpcs/autoload.php:2
PHP  12. spl_autoload_call() /home/sakona/dev/wpcs/WordPress/AbstractClassRestrictionsSniff.php:21
PHP  13. PHP_CodeSniffer\Autoload::load() /home/sakona/dev/wpcs/WordPress/AbstractClassRestrictionsSniff.php:21
PHP  14. PHP_CodeSniffer\Autoload::loadFile() phar:///usr/local/bin/phpcs/autoload.php:2
PHP  15. include() phar:///usr/local/bin/phpcs/autoload.php:2
PHP  16. spl_autoload_call() /home/sakona/dev/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php:27
PHP  17. PHP_CodeSniffer\Autoload::load() /home/sakona/dev/wpcs/WordPress/AbstractFunctionRestrictionsSniff.php:27
PHP  18. PHP_CodeSniffer\Autoload::loadFile() phar:///usr/local/bin/phpcs/autoload.php:2
PHP  19. include() phar:///usr/local/bin/phpcs/autoload.php:2
```

Please get help on this.
Thanks,

**Comment by jrfnl** [comment] 2017-11-16 09:10
What version of WPCS are you using ?

**Comment by sakonachhoeurng** [comment] 2017-11-16 09:11
I follow this command to install wpcs `composer create-project wp-coding-standards/wpcs --no-dev`

**Comment by jrfnl** [comment] 2017-11-16 13:08
@sakonachhoeurng The information you provide contradicts each other, so I'm not sure how I can help.

In your original message you say you are using PHPCS 2.9.0, but the stack trace shows that you are in actual fact using PHPCS 3.x.
The screenshot from your Composer install also shows it installing PHPCS 3.1.1.

You then state that you expect you are using the latest WPCS and the Composer install screenshot confirms that, but the error stack trace is typical for WPCS < 0.13.0.

Please run the below commands and post the output here to see if we can get some clarity.
1. Let's confirm which version of PHPCS you are in actual fact using: `phpcs -v`
    There may be more than one install one your system and it might be that the install being used is not the install as pulled in by Composer.
2. Let's see what version of WPCS you are using: `phpcs -e --standard=WordPress`.
    Based on the sniff list this returns we should be able to get a good idea of what version of WPCS is actually being used.

**Comment by GaryJones** [comment] 2017-11-16 13:22
@sakonachhoeurng Check if using `vendor/bin/phpcs` differs from `phpcs`.

**Comment by sakonachhoeurng** [comment] 2017-11-17 01:52
my `phpcs` is `/usr/local/bin/phpcs`

**Comment by sakonachhoeurng** [comment] 2017-11-17 01:57
@jrfnl, thanks for explaining.
my `phpcs` is 3.00.
You can check on screenshot
![image](https://user-images.githubusercontent.com/12217854/32925555-10f7e722-cb75-11e7-9ec1-74da7691b55f.png)
-----------------------------------------------
Therefore, I install `squizelab` on my project with `composer.json` I install it 2.9, but when I run command `composer create-project wp-coding-standards/wpcs --no-dev`
Then it also install version 3.0.0

**Comment by sakonachhoeurng** [comment] 2017-11-17 02:15
Hi @jrfnl , @GaryJones 
From now, I install `wpcs` to my project directory, then `vendor/bin/phpcs` version is `2.9.0`,
but still got error when I run `phpcs -e --standard=WordPress`

**Comment by jrfnl** [comment] 2017-11-17 02:25
There is no version of WPCS which is compatible with PHPCS 3.0.0 as that version contained quite some bugs still.

You either need 2.9.0/2.9.1 or version 3.0.2 or higher. For the best results, always use an up-to-date version of PHPCS, which would currently be version 3.1.1.

> but still got error when I run `phpcs -e --standard=WordPress`

What error do you get when you run `phpcs -e --standard=WordPress` ?

And can you try to run `phpcs -i` to see if the WPCS standards are registered correctly in the install you are using ?

You'll probably will need to run both commands as `vendor/bin/phpcs`.

**Comment by sakonachhoeurng** [comment] 2017-11-17 02:27
Hey guide, 

When I try my step
1. Install wpcs to my project directory
2. Make `vendor/bin/phpcs` configure with `vendor/bin/phpcs --config-set installed_paths wpcs`
3. Then run `vendor/bin/phpcs -e --standard=Wordpress` that list all standard contain sniff
4. Run `vendor/bin/phpcs -w --standard=Wordpress wp-content/themes/kymenlaaksonjate/template-service.php` that work for me now.
5. That work for me, 
Cheers,

**Comment by jrfnl** [comment] 2017-11-17 02:34
Great to hear! Does that mean we can close the issue ?

**Comment by sakonachhoeurng** [comment] 2017-11-17 02:35
I think the best way for installation, you should follow my step as installation, I try to follow your installation step, but do not understand and not so clear.

You can close the ticket.

**Comment by sakonachhoeurng** [comment] 2017-11-17 02:55
Hi @jrfnl ,

I also have question to `phpcs` version 2.9 and 3.0.x what different checkstyle error.
I test that is different fro 2.9 and 3.x

**Comment by jrfnl** [comment] 2017-11-17 03:11
> I also have question to phpcs version 2.9 and 3.0.x what different checkstyle error.
> I test that is different fro 2.9 and 3.x

@sakonachhoeurng What is your question ? This is a bit too vague for me to figure out what you mean ?

**Comment by sakonachhoeurng** [comment] 2017-11-17 03:28
I mean when I run checkstyle from 2.9 that saw errors, but when I run with 3.x that error in 2.9 not exist anymore.

**Comment by jrfnl** [comment] 2017-11-17 03:57
Without more detailed information about the errors you saw and the code this applied to, I can not tell you what is going on.

It may be a bug, but it may also be that you are seeing the effects of bugfixes which have been made to counter false positives.

As a rule of thumb, I'd say: always use the latest stable release ( 3.1.1 in this case).
All the same, I am curious to hear more about the differences you see in the results.

**Comment by sakonachhoeurng** [comment] 2017-11-17 07:30
It may make you confuse. Not mean it error when I run with 2.9. I mean that when I run checkstyle on version 2.9
That list error from `php file` or directory that I want to check codestyle.
Then when I run with version 3.x the error list from php file not exist anymore for new phpcs version
 sth like this
![image](https://user-images.githubusercontent.com/12217854/32935669-ba926a40-cba3-11e7-97c4-0419fe19fe15.png)

Then those error above will not happen on phpcs 3.x

I hope you understand.
My question, and I wonder how can I use between this 2 version.

**Comment by jrfnl** [comment] 2018-03-01 07:12
@sakonachhoeurng I honestly still don't understand what you mean.

What is this `checkstyle` you are talking about ? If that's another tool, then you may ask for support from them.

**Comment by GaryJones** [comment] 2018-03-01 09:16
Checkstyle is a tool for checking code style. It can be used in an ANT environment, like Jenkins.

PHPCS can output with a `--report=checkstyle` (XML-based), which can then be read, analysed and reported by Checkstyle or other plugins as if it was a report from Checkstyle itself.

It sounds like using PHPCS 2.9 is not producing the same errors as PHPCS 3.*.

@sakonachhoeurng We're sorry, but it's really hard to be able to narrow down what the problem might be from the limited information you've provided. Since it seems the issue is not directly related to **WPCS**, I suggest you raise it in the [PHPCS repo](https://github.com/squizlabs/PHP_CodeSniffer/issues/).

**Comment by jrfnl** [comment] 2019-03-07 03:47
Closing for lack of response.
If this is still an issue, please provide the additional information requested and we can reopen the issue.

**Closed by jrfnl** 2019-03-07 03:47 UTC
Labels: Type: Question
