### ISSUE TITLE
False positive / VIP.ValidatedSanitizedInput

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#359] opened 2015-04-18 16:09 UTC
```php
if ( ! isset( $_POST['shortcode'] ) || $_POST['shortcode'] === '' ) {
	exit( '-1' );
}
```

IMHO the above usage should be ok. Yes, the value is not sanitized, but this comparison does not yield a situation where the non-sanitized variable could in any way be dangerous.

`Detected usage of a non-sanitized input variable: $_POST (WordPress.VIP.ValidatedSanitizedInput.InputNotSanitized)`

**Comment by JDGrimes** [comment] 2015-04-18 16:13
Duplicate of #186.

**Closed by JDGrimes** 2015-04-18 16:13 UTC
Labels: duplicate

**Comment by jrfnl** [comment] 2015-04-18 16:28
Good catch, thanks!
