### ISSUE TITLE
Be compatible with PHP_CodeSniffer v3

### ISSUE THREAD

**Issue by fulldecent** [WordPress-Coding-Standards/WordPress-Coding-Standards#938] opened 2017-05-04 15:16 UTC
Dependency on the old version is expressed here:

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/master/composer.json#L14

However a new version was just released here:

https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0

Therefore we are now depending on an old version.

**Comment by jrfnl** [comment] 2017-05-04 15:20
Closing as duplicate of #718.

WPCS is currently not (yet) compatible with PHPCS 3.0.

**Closed by jrfnl** 2017-05-04 15:20 UTC
Labels: Status: Duplicate
