### ISSUE TITLE
Missing trailing semi-colon doesn't trigger a warning

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#465] opened 2015-10-02 22:14 UTC
Not sure if this should go upstream to PHPCS or not.

The following line, which does not contain a terminating semi-colon, doesn't trigger a warning:

`<?php my_function() ?>`

Should it?

**Comment by JDGrimes** [comment] 2015-10-02 22:19
It is valid PHP. I don't know if the WordPress standards have a preference one way or the other. My personal preference is to always use the semicolon. That also matches best practice in JS.

**Comment by westonruter** [comment] 2015-10-02 22:23
I thought for sure there was a sniff for this already upstream, but all I see is one specific for CSS: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/CSS/MissingColonSniff.php

**Comment by joeyred** [comment] 2015-11-17 01:20
I ran into this problem with a missing semicolon on a return statement. `return $content` didn't register as an error. So I think the question is still valid.

Considering this causes a fatal error from WP_Debug i would think my linter should get it. 

Any more info on this?

**Comment by jrfnl** [comment] 2016-07-11 12:35
This upstream sniff might help detect this (and other parse error issues), though I haven't tested it: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/SyntaxSniff.php

**Comment by jrfnl** [comment] 2016-12-27 16:23
The PHP syntax sniff has been in `extra` for a while now. While it won't catch the original issue (not a parse error), is that sufficient and can this issue be closed or should we keep the issue open & address the original issue still ?

**Comment by jrfnl** [comment] 2017-06-17 18:54
Done some more checking and found a sniff which will handle this, though it does a lot more than just check for the semi-colon: `Squiz.PHP.EmbeddedPhp.NoSemicolon`.

If we would include this sniff, which of the other messages the sniff throws should be excluded ?

Ref: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php

**Comment by JDGrimes** [comment] 2017-06-17 19:51
The errors are (ones that I would include marked with *):

For multiline blocks:

-  *Empty embedded PHP tag found
- *Opening PHP tag must be on a line by itself
- Blank line found at start of embedded PHP content
- First line of embedded PHP code must be indented %s spaces; %s found
- Opening PHP tag indent incorrect; expected no more than %s spaces but found %s
- *Closing PHP tag must be on a line by itself
- Blank line found at end of embedded PHP content

For single-line blocks:

- *Expected 1 space after opening PHP tag; %s found
- *Inline PHP statement must end with a semicolon
- *Inline PHP statement must contain a single statement; %s found
- *Expected 1 space before closing PHP tag; %s found

**Comment by jrfnl** [comment] 2017-06-17 20:19
I second your assessment @JDGrimes

> Empty embedded PHP tag found

A check for that is also included in the new empty statements sniff: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/980

Other than that, I've just ran the unit test file from the `Squiz.PHP.EmbeddedPhp` sniff through the `WordPress` standard and apart from some notices from the `Generic.WhiteSpace.ScopeIndent.Incorrect` sniff/error code, none of the other things checked by the `Squiz.PHP.EmbeddedPhp` sniff would cause duplicate messages ATM (i.e. none of the other things are being checked for in WPCS).

**Comment by jrfnl** [comment] 2017-06-17 20:24
Just a thought: I'm wondering whether actually *enabling* (some of) the indent errors from this sniff might solve some of the weird issues we've been seeing caused by the auto-fixer from the `Generic.WhiteSpace.ScopeIndent` sniff.

**Closed** 2017-06-20 12:06 UTC
Labels: Type: Question

**Comment by Rarst** [comment] 2018-02-15 14:18
Late to the discussion, but I am against enforcing semicolon in cases like originally stated (`<?php my_function() ?>`).

It is explicitly valid on language level (closing tag always implies statement termination) and, in my experience, is good and encouraged practice in template contexts.

**Comment by jrfnl** [comment] 2018-02-15 16:47
@Rarst You can always silence that error for your projects from a custom ruleset and/or using `exclude=sniffname` from the command line.
