### ISSUE TITLE
`WordPress.Arrays.ArrayDeclarationSpacing` fails on some files (fixer conflict)

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#968] opened 2017-06-16 10:45 UTC
While running this rule on Core, it causes some files to exceed the pass limit. It seems to be getting stuck in a loop of changing how lines are indented, as each rule violates some other rule.

For example, `src/wp-content/themes/twentyeleven/404.php` will get stuck.

**Comment by JDGrimes** [comment] 2017-06-16 13:16
Minimum reproducible code:

```php
the_widget( 'WP_Widget_Recent_Posts', array( 'number' => 10 ), array( 'widget_id' => '404' ) );
```

Basically the issue is that there are two associative arrays on the same line.

I think that the sniff that is actually `WordPress.Arrays.ArrayDeclarationSpacing` that is causing the issue. It is trying to fix the second array to be multiline after fixing the first array, and that is where it fails. Remove the second associative array and the code is fixed without problem.

**Comment by jrfnl** [comment] 2017-06-16 14:40
I'll see if I can get a fix sorted later today.

**Comment by jrfnl** [comment] 2017-06-17 11:38
I've been investigating this issue and I can confirm @JDGrimes 's analysis. The issues is in the `WordPress.Arrays.ArrayDeclarationSpacing` sniff, but only when used in combination with an array passed as a parameter in a function call.

The conflict is with the `PEAR.Functions.FunctionCallSignature` sniff with the _"Multi-line function call not indented correctly"_ error.

My current line of thinking for a solution is:
* Check if the associative array declaration is found within nested parenthesis (like with a function call)
* If so, add a new line before the `array` keyword or `[` array opener.
* I'm also thinking of removing the indenting from the fixer there and leaving that completely up to the `ArrayIndentation` sniff - which didn't yet exist when the fixer was added to the `WordPress.Arrays.ArrayDeclarationSpacing` sniff

Will need to play with this for a bit & do a lot of testing to see if this will work.

**Comment by pento** [comment] 2017-06-25 07:15
A variation of this I've run into, which looks to have the same cause:

```php
a( array( 'b' => 'c' ), d( array( 'e' => 'f' ) ) );
```

**Comment by jrfnl** [comment] 2017-06-30 16:01
@pento Yes, that definitely is one of the same kind as well.

I'm looking into fixing this, but there are three ways I can go about this and I'd like some opinions on what is preferred:
```php
a( true, array( 'b' => 'c' ), d( array( 'e' => 'f' ), '' ), 123 );
```
If an associative array is found as a parameter within a function call...
1. ... throw an error, but do not auto-fix it. (code would remain unchanged)
```php
a( true, array( 'b' => 'c' ), d( array( 'e' => 'f' ), '' ), 123 );
```
2. ... make sure that the array parameter starts on a new line, but don't change any of the other arguments (this may be then changed by another sniff anyhow, but I'd need to test that)
```php
a( true,
	array(
		'b' => 'c',
	), d(
		array(
			'e' => 'f',
		), '' ), 123 );
```
3. ... change the function call to be a "proper" multi-line function call with each argument on a new line.
```php
a(
	true,
	array(
		'b' => 'c',
	),
	d(
		array(
			'e' => 'f',
		),
		''
	),
	123
);
```

Opinions ?

**Comment by JDGrimes** [comment] 2017-06-30 16:14
Perhaps best to just throw an error here. Although option 3 is kind of the goal end result, I think that we probably don't want the sniff to be that opinionated about unrelated stuff. I'd possibly go for option 2 if other sniffs would indeed clean it up a bit.

**Comment by jrfnl** [comment] 2017-06-30 17:51
Just ran a number of tests with option 2 and 3:

Option 2 - would still result in a conflict

Option 3 - can solve the conflict, but only if we also add a new line before the function call close parenthesis.

On a related note: I believe we should ignore associative arrays which are default values in a function declaration for the fixer part (and maybe even for the error throwing too ? )
```php
function foo( $config = array( 'b' => 'c' ), 123 ) {}
```

**Comment by JDGrimes** [comment] 2017-06-30 18:10
> On a related note: I believe we should ignore associative arrays which are default values in a function declaration for the fixer part (and maybe even for the error throwing too ? )

+1

**Comment by GaryJones** [comment] 2017-06-30 18:25
In an ideal world, I'd want to see 3 as the end result too.

And +1 for ignoring assoc arrays when they are default values (though there is an [argument](https://github.com/kalessil/phpinspectionsea/blob/master/docs/code-style.md#non-null-parameters-default-value) that default values should only ever be `null`, and that logic like default values should be handled inside the function, not as part of its signature).

**Comment by jrfnl** [comment] 2017-06-30 18:37
@JDGrimes @GaryJones Thanks for your input. I've got option three working, so I'll tidy up, run some more tests and will pull it if I don't encounter any more issues with it.

> (though there is an argument that default values should only ever be null, and that logic like default values should be handled inside the function, not as part of its signature).

That... is a completely different and unrelated issue IMO and pretty opinionated at that. Thinking of WP core and the "average" level of abstraction in themes and plugins, I don't think that a sniff for something like that would be appropriate for WPCS anyhow. At least not for the foreseeable future.

**Comment by jrfnl** [comment] 2017-06-30 21:49
Ok, done some more investigation and the root cause of the issue is that the core ruleset excludes two checks from the `PEAR.Functions.FunctionCallSignature` sniff.

```xml
	<rule ref="PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket">
		<severity>0</severity>
	</rule>
	<rule ref="PEAR.Functions.FunctionCallSignature.CloseBracketLine">
		<severity>0</severity>
	</rule>
```

These exclusions were added at the same time as the WPCS version of that sniff was removed in favour of the upstream sniff in 2014 by @westonruter If I understand correctly, this was to allow for code like:

```php
foreach ( $core_options as $option_name => $real_value ) {
    add_filter( "pre_option_{$option_name}", function( $value ) use ( $real_current_blog_id, $real_value ) {
        if ( get_current_blog_id() == $real_current_blog_id ) {
            return $real_value + 1;
        } else {
            return $value;
        }
    } );
}
```

Removing the exclusions solves the issue without any further code changes in the `WordPress.Arrays.ArrayDeclarationSpacing` sniff and would result in the above snippet being _fixed_ to the below which, to be honest, looks better than before to me:

```php
foreach ( $core_options as $option_name => $real_value ) {
	add_filter(
		"pre_option_{$option_name}", function( $value ) use ( $real_current_blog_id, $real_value ) {
			if ( get_current_blog_id() == $real_current_blog_id ) {
				return $real_value + 1;
			} else {
				return $value;
			}
		}
	);
}
```

Refs:
* https://github.com/squizlabs/PHP_CodeSniffer/pull/330
* https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/272

**Comment by GaryJones** [comment] 2017-06-30 22:09
> Oh and the snippet I used earlier as an example would be fixed - without conflicts - like this when the two exclusions would be removed:

Not quite the same as your initial example of 3 - breaks on function calls and array keys, but not on parent function parameters. I'd prefer it in a single line compared to this.

**Comment by JDGrimes** [comment] 2017-06-30 22:12
I have no problem with the updated fix. Personally, if a function call has multiline parameters, I always put each parameter on its own line. I don't know if there is a sniff that enforces that, but I think code like your second example is unreadable.

**Comment by jrfnl** [comment] 2017-06-30 22:43
The thing is, if exclusions are causing the conflicts in fixers, then we should address that problem and not try to work around it.

That means in practice any of the following solutions:
* Remove exclusions & live with the consequences
* If possible/relevant, pull fixes upstream if that would ease the pain (though that's awkward now with PHPCS 2.x vs 3.x)
* Or find or write a better sniff for the sniff (or parts thereof) where we needed the exclusions

Adjusting an unrelated sniff to work round exclusions made to another sniff feels like the wrong way to go.

**Comment by jrfnl** [comment] 2017-07-08 15:02
@westonruter Have you got an opinion on this as you added the original exclusions ?

**Comment by westonruter** [comment] 2017-07-09 02:59
If these exclusions are removed, would it not cause these very common core WP patterns to be marked as invalid?

```php
	$atts = shortcode_atts( array(
		'order'      => 'ASC',
		'orderby'    => 'menu_order ID',
		'id'         => $post ? $post->ID : 0,
		'itemtag'    => $html5 ? 'figure'     : 'dl',
		'icontag'    => $html5 ? 'div'        : 'dt',
		'captiontag' => $html5 ? 'figcaption' : 'dd',
		'columns'    => 3,
		'size'       => 'thumbnail',
		'include'    => '',
		'exclude'    => '',
		'link'       => ''
	), $attr, 'gallery' );
```

and

```php
	$link = sprintf( '<a href="%1$s" title="%2$s" rel="author">%3$s</a>',
		esc_url( get_author_posts_url( $authordata->ID, $authordata->user_nicename ) ),
		/* translators: %s: author's display name */
		esc_attr( sprintf( __( 'Posts by %s' ), get_the_author() ) ),
		get_the_author()
	);
```

and

```php

		$set = wp_parse_args( $settings, array(
			'wpautop'             => true,
			'media_buttons'       => true,
			// ...
		) );
```

**Comment by jrfnl** [comment] 2017-07-09 03:18
@westonruter Yes it would, though we could leave the exclusions for "normal" runs and only remove them for the fixer by adding `phpcs-only="true"` to the exclusions.
See: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml#selectively-applying-rules

The alternative would be option 1 from https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/968#issuecomment-312306914 - throw an error (or warning), but don't auto-fix associative arrays which are parameters in a function call.

Or write a completely different sniff for function call signatures as the PEAR one basically presumes either single-line calls or multi-line calls where each parameter is placed on a new line, but does not allow for a mix.

As they currently are, the WP coding standards allow multi-line function calls with an arbitrary number or parameters per line (which is not in line with the PEAR sniff we're using).

Whether this is a conscious choice or a hiatus in the Coding Standards should inform the direction to take.

**Comment by westonruter** [comment] 2017-07-09 03:26
I don't think we'd want there to be warnings or errors ever to surface due to these sniffs, since this coding style is pervasive. For example: https://codex.wordpress.org/Function_Reference/add_shortcode

So excluding them _and_ removing them from the fixer seems like the best way to go in the short term, if I understand the options sufficiently.

**Comment by jrfnl** [comment] 2017-07-09 04:01
> So excluding them and removing them from the fixer

I'm not sure I understand what you mean by that. Could you be a bit more specific ?

**Comment by westonruter** [comment] 2017-07-09 04:11
What you said:

> we could leave the exclusions for "normal" runs and only remove them for the fixer

**Comment by jrfnl** [comment] 2017-07-09 05:08
Ok. Pr to that effect has been pulled as #1020

**Closed** 2017-07-09 17:11 UTC
Labels: Status: Investigation, Type: Bug

**Comment by Moehan1977** [comment] 2019-07-13 09:48
How do fix this error (Associative array parameters required)
