### ISSUE TITLE
Placeholders in sprintf function is not replacing correctly

### ISSUE THREAD

**Issue by ravinderk** [WordPress-Coding-Standards/WordPress-Coding-Standards#726] opened 2016-12-13 06:46 UTC
#### Current
<img width="759" alt="screen shot 2016-12-09 at 11 10 40 pm" src="https://cloud.githubusercontent.com/assets/1784821/21130333/aeea185e-c12d-11e6-9dd7-d0dc1446d4e0.png">

#### Warning after checking
<img width="667" alt="screen shot 2016-12-09 at 11 11 06 pm" src="https://cloud.githubusercontent.com/assets/1784821/21130335/aeed6cfc-c12d-11e6-9029-04774827b136.png">

#### Wrong auto fixing
<img width="752" alt="screen shot 2016-12-09 at 11 10 51 pm" src="https://cloud.githubusercontent.com/assets/1784821/21130334/aeec29c8-c12d-11e6-952a-ab487b68966f.png">

**Comment by GaryJones** [comment] 2016-12-14 00:43
@ravinderk The unit tests I wrote against the develop branch all pass, but fail when added to the 0.10.0 tag you have as your current commit. Whatever the issue was, it looks like it's already been fixed. Please check out the develop branch and run your code against that.

**Comment by jrfnl** [comment] 2016-12-14 05:49
Closing as duplicate of #698 which was fixed in #710

**Closed by jrfnl** 2016-12-14 05:49 UTC
Labels: Status: Investigation, Type: Bug
