### ISSUE TITLE
customVariablesWhitelist would benefit from scoping

### ISSUE THREAD

**Issue by moorscode** [WordPress-Coding-Standards/WordPress-Coding-Standards#1102] opened 2017-08-15 13:05 UTC
We have currently implemented some exceptions for array properties which come from an external object. As we don't have control over the property styling, this seems like a good way to prevent any errors.

```xml
<rule ref="WordPress.NamingConventions.ValidVariableName">
        <properties>
            <property name="customVariablesWhitelist" type="array" value="pageUrl,responseCode,siteEntry,siteUrl,countPerTypes,urlCrawlErrorSample,buyUrl,infoUrl" />
        </properties>
</rule>
```

What I see happening is, that the properties on `any` array will be accepted.
So if somebody would use `responseCode` on an object internally, it would be not be caught.

Perhaps it would be possible to provide a function or class scope in which this whitelist will be enforced.

**Comment by jrfnl** [comment] 2019-03-30 11:51
Duplicate of #1623 

While #1623 is more recent, it contains more information about a possible solution direction, so I'm closing this issue in favour of continuing the discussion in #1623.

**Closed by jrfnl** 2019-03-30 11:51 UTC
Labels: Type: Enhancement
