### ISSUE TITLE
Potential false positives for ValidatedSanitizedInputSniff

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#1509] opened 2018-10-19 18:34 UTC
Reported by @rinatkhaziev:

https://github.com/10up/safe-redirect-manager/blob/9fc66f2d9acf39ad2af9a42bc3d4865907b23608/inc/classes/class-srm-post-type.php#L59

https://github.com/10up/safe-redirect-manager/blob/9fc66f2d9acf39ad2af9a42bc3d4865907b23608/inc/classes/class-srm-post-type.php#L236

Being reported as violations for ValidatedSanitizedInput (not sure of the exact error code), and thought to be false positives.

**Comment by jrfnl** [comment] 2018-10-19 18:54
@GaryJones That's a bit vague... I would suggest closing this issue until more detailed info is available as I suspect - by just glancing at the code - that this will be a duplicate issue for #1497. If not, then we need to know what the user thinks is wrong with the sniff.

As things stand, this issue is not actionable.

**Closed** 2018-10-20 12:19 UTC
Labels: Status: Needs Investigation, Type: Bug

**Comment by jrfnl** [comment] 2019-03-29 09:22
FYI: As #1497 was not reproducible, I have also run some tests with the code linked above and still can't reproduce the issue.
