### ISSUE TITLE
Running phpcbf using the WordPress standard causes errors when a single line comment is followed by a multi line comment.

### ISSUE THREAD

**Issue by shawcohn** [WordPress-Coding-Standards/WordPress-Coding-Standards#478] opened 2015-10-23 00:15 UTC
Running phpcbf using the WordPress standard on a file that has the following code causes errors:
```
<?php
$foo  = ''; // Some text
/** Some more text **/
```

**Comment by westonruter** [comment] 2015-10-23 00:16
What errors?

**Comment by JDGrimes** [comment] 2015-10-23 12:43
When I run phpcbf on that code, it gives this:

```php
<?php
$foo = ''; // Some text
	* / Some more text * * /
```

Which will cause PHP syntax errors. I'm using PHPCS 2.3.2, but I'll try to update to the latest version and see if the issue still exists. I have a feeling that this might be an issue in PHPCS itself, but I need to investigate further. @shawcohn, what version of PHPCS are you running?

**Comment by JDGrimes** [comment] 2015-10-23 14:05
I've tested this with PHPCS 2.3.4 and I still experience the issue.

It does appear to be related to our standard somehow, although the problem is not caused by our sniffs. The problem sniff appears to be `Squiz.Commenting.BlockComment.WrongEnd`.

When I run `phpcbf --standard=WordPresss test.php` I get this problem, but not when I run `phpcbf --standard=Squiz test.php`.

I have a feeling that the `Squiz.Commenting.BlockComment` sniff is expecting another sniff to be present that we don't include in our standard. Or, possibly it is some other configuration issue.

**Comment by shawcohn** [comment] 2015-10-23 17:02
@JDGrimes, we are using PHPCS 2.3.3.

Thanks

**Comment by JDGrimes** [comment] 2015-10-23 22:11
This is indeed a bug in PHPCS. I've submitted https://github.com/squizlabs/PHP_CodeSniffer/issues/748 to fix it. I'm going to close this issue since the bug is really upstream.

**Closed by JDGrimes** 2015-10-23 22:11 UTC
Labels: bug

**Comment by JDGrimes** [comment] 2015-11-02 12:54
@shawcohn My fix for this has been merged into PHPCS, and will be part of the next PHPCS release.

**Comment by shawcohn** [comment] 2015-11-10 19:45
@JDGrimes Great, thanks.
