### ISSUE TITLE
PHP indentation within HTML files

### ISSUE THREAD

**Issue by shadyvb** [WordPress-Coding-Standards/WordPress-Coding-Standards#122] opened 2013-11-04 20:40 UTC
This is somewhat messy with current sniffs, do we have some rule that we can test against and maybe edit sniffs to enforce it ?

**Comment by JDGrimes** [comment] 2015-03-22 21:41
I can't reproduce these anymore, and the upstream version of the `ScopeIndent` sniff is being used now instead (see #250). Closing.

**Closed by JDGrimes** 2015-03-22 21:41 UTC
