### ISSUE TITLE
EscapeOutputSniff flagging non-output statements

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#169] opened 2014-05-01 08:01 UTC
The EscapeOutputSniff is for some reason flagging statements such as:

```php
$links[ __( 'Edit Menu', 'stream' ) ] = admin_url( 'nav-menus.php?action=edit&menu=' . $record->object_id );
$links[ __( 'Edit Widget Area', 'stream' ) ] = admin_url( 'widgets.php#' . $sidebar );
$x = array(
    'activate' => wp_nonce_url( add_query_arg( array( 'action' => 'activate', 'plugin' => $extension->post_meta->plugin_path[0], 'plugin_status' => 'all', 'paged' => '1' ), self_admin_url( 'plugins.php' ) ), 'activate-plugin_' . $extension->post_meta->plugin_path[0] ),
    'nonce'  => 'install-plugin_' . $plugin['slug'],
);
```

**Comment by JDGrimes** [comment] 2015-04-01 22:10
I can't reproduce this anymore, so I'm going to close it as fixed. 

I had experienced similar issues before, and I think that they were caused by `__()` and other translation functions being treated as if they were output functions (see #315) in combination with a bug with the sniff not properly terminating checking at the end of the function.

**Closed by JDGrimes** 2015-04-01 22:10 UTC
Labels: extra
