### ISSUE TITLE
Fix "// Silence is golden" newline requirement

### ISSUE THREAD

**Issue by jtsternberg** [WordPress-Coding-Standards/WordPress-Coding-Standards#908] opened 2017-04-03 18:56 UTC
e.g. https://github.com/WebDevStudios/CMB2/pull/905

This single-line file is a WP staple, and it would seem should be granted an exception.

**Comment by GaryJones** [comment] 2017-04-04 07:34
I'm not in favour of granting an exception, even if Juliette knew how :-)

I wouldn't even consider it a staple - just an anti-pattern that less knowledgable folks appear to have copied. The only purpose of empty index.php files is to try and avoid directory listings - and that's something that should be fixed at the server level, at least at the web root directory, and not assume that every single plugin and every single theme, and all WP core folders include an empty index.php file (Hint: they don't - it's not a requirement because it's the wrong solution).

Plugin and theme authors should not be trying to compensate for a poor server configuration (and hey, someone might _want_ to show their index for a directory).

For Apache, it's a single line that usually even works in the site root `.htaccess` and will cascade down to subdirectories:

```
Options -Indexes
```

**Comment by JDGrimes** [comment] 2017-04-04 12:43
Closing as a duplicate of #451.

And I agree with @GaryJones on this: `index.php` unnecessary, and it is *not* used by WordPress (except in `wp-content`).

**Closed by JDGrimes** 2017-04-04 12:43 UTC
Labels: Status: Awaiting Feedback

**Comment by jtsternberg** [comment] 2017-04-04 13:01
Sounds good. Thanks all.
