### ISSUE TITLE
Multiple Fatal PHP errors

### ISSUE THREAD

**Issue by ChrisWiegman** [WordPress-Coding-Standards/WordPress-Coding-Standards#947] opened 2017-05-10 16:30 UTC
Environment: Phpcs 3.0.1 and phpcs 3.0.0 on PHP 7.1
WPCS versions: develop and master

Attempting to invoke WordPress coding standards on any file results in numerous fatal errors:

```
PHP Fatal error:  Class 'WordPress_AbstractArrayAssignmentRestrictionsSniff' not found in .../wpcs/WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php on line 24

Fatal error: Class 'WordPress_AbstractArrayAssignmentRestrictionsSniff' not found in .../wpcs/WordPress/Sniffs/Arrays/ArrayAssignmentRestrictionsSniff.php on line 24

PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found in .../wpcs/WordPress/Sniffs/Files/FileNameSniff.php on line 25
```

This seems to just have popped up this morning

**Comment by westonruter** [comment] 2017-05-10 17:04
Downgrade to PHPCS 2.9 for now.

Closing as duplicate of #944, #938, #872, #718 etc

**Closed by westonruter** 2017-05-10 17:04 UTC
Labels: Status: Duplicate
