### ISSUE TITLE
Document various comments you can use in the README

### ISSUE THREAD

**Issue by danielbachhuber** [WordPress-Coding-Standards/WordPress-Coding-Standards#361] opened 2015-04-21 22:10 UTC
As a newbie user, I'm discovering all of the various comments I can use to change behavior by reading the code.

It would be nice if comments like `// WPCS: input var okay` and `// @codingStandardsIgnoreStart` were documented in the readme. Not sure what else I'm missing.

**Comment by JDGrimes** [comment] 2015-04-21 22:15
:+1: 

`@codingStandardsIgnoreStart` isn't ours though, it is built into PHPCS. But it might be worth mentioning as well. 

There is a [wiki page](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Flagged-superglobal-usage-in-WordPress-VIP) that mentions one of these. Maybe we should create a wiki page for all of them and link to it in the readme?

**Comment by danielbachhuber** [comment] 2015-04-21 22:16
> Maybe we should create a wiki page for all of them and link to it in the readme?

That would be great.

**Comment by danielbachhuber** [comment] 2015-04-21 22:19
@JDGrimes If you have a moment to help out, I'd love your thoughts on  https://github.com/fusioneng/Shortcake/pull/290#issuecomment-94959102

**Comment by JDGrimes** [comment] 2015-04-21 22:22
@danielbachhuber on it.

**Comment by JDGrimes** [comment] 2015-04-21 22:23
BTW, I think the wiki is open to anyone, so if you want to start a page on the comments, feel free.

**Comment by JDGrimes** [comment] 2015-04-21 22:33
@danielbachhuber Gotta run. I'll look at that more tomorrow if you need me to.

**Comment by JDGrimes** [comment] 2015-04-22 12:55
PHPCS also supports documentation for sniffs (e.g.: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Docs/Classes/DuplicateClassNameStandard.xml). Maybe if we added these docs for our sniffs it would be helpful as well. I wonder if maybe there is a script that converts these docs into website—then we could use gh-pages to host the docs for the sniffs on the web too, and not have to maintain them in two locations.

**Comment by danielbachhuber** [comment] 2015-04-22 14:55
Given how [easy it is to run into errors with sanitization / validation sniffs](https://github.com/fusioneng/Shortcake/pull/290#issuecomment-95160168), it would be good to have copious documentation on the appropriate code patterns for sanitization / validation.

**Comment by JDGrimes** [comment] 2015-09-09 18:50
Closing this as a duplicate of #446, since @johnbillion has compiled a list for us there as a start.

**Closed by JDGrimes** 2015-09-09 18:50 UTC
Labels: enhancement
